### ISSUE TITLE
Input and Output Explaination

### ISSUE THREAD

**Issue by firstimpressionmusic** [carefree0910/TextClassification#1]
Can you please explain the input and output? What the code do, etc?

**Comment by firstimpressionmusic** [comment]
Also I get this error

## #     Main     # Progress bar initialized  ##
Generating Dataset...
Done

## # SKLinearSVM  # Progress bar initialized  ##Traceback (most recent call last):
  File "/Users/andrew/PycharmProjects/TextClassification11/SkRun.py", line 81, in <module>
    run("SVM")
  File "/Users/andrew/PycharmProjects/TextClassification11/SkRun.py", line 60, in run
    rs = main(_clf)
  File "/Users/andrew/PycharmProjects/TextClassification11/SkRun.py", line 41, in main
    y_pred = clf.predict(x_test)
  File "/Users/andrew/PycharmProjects/111/venv/lib/python3.8/site-packages/sklearn/linear_model/_base.py", line 293, in predict
    scores = self.decision_function(X)
  File "/Users/andrew/PycharmProjects/111/venv/lib/python3.8/site-packages/sklearn/linear_model/_base.py", line 268, in decision_function
    X = check_array(X, accept_sparse='csr')
  File "/Users/andrew/PycharmProjects/111/venv/lib/python3.8/site-packages/sklearn/utils/validation.py", line 583, in check_array
    raise ValueError("Found array with %d sample(s) (shape=%s) while a"
ValueError: Found array with 0 sample(s) (shape=(0, 156)) while a minimum of 1 is required.

Process finished with exit code 1
